apiVersion: v1
kind: Pod
metadata:
  name: pod-redhat-test
  namespace: test
  labels:
    app: test-redhat
spec:
  containers:
  - name: ubi-container
    image: registry.access.redhat.com/ubi9/ubi-minimal:latest
    command: ["/bin/sh", "-c", "while true; do echo 'Probando conexion Red Hat Registry'; sleep 30; done"]
  restartPolicy: Always
