apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend
  namespace: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: python-web
        image: registry.redhat.io/rhel8/python-39:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            cat <<EOF > app.py
            from flask import Flask
            import mysql.connector
            import os

            app = Flask(__name__)

            @app.route('/')
            def hello():
                try:
                    conn = mysql.connector.connect(
                        host=os.environ.get('DB_HOST'),
                        user=os.environ.get('DB_USER'),
                        password=os.environ.get('DB_PASSWORD'),
                        database=os.environ.get('DB_NAME')
                    )
                    return "<h1>Conexión Exitosa!</h1><p>La web en OpenShift se conectó a MariaDB.</p>"
                except Exception as e:
                    return f"<h1>Error de Conexión</h1><p>{str(e)}</p>"

            if __name__ == '__main__':
                app.run(host='0.0.0.0', port=8080)
            EOF
            pip install mysql-connector-python flask
            python app.py
        env:
        - name: DB_HOST
          value: "mariadb-service"
        - name: DB_USER
          value: "user1"
        - name: DB_PASSWORD
          value: "password123"
        - name: DB_NAME
          value: "testdb"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: test
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: web-route
  namespace: test
spec:
  to:
    kind: Service
    name: web-service
  port:
    targetPort: 8080