apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-test
  namespace: test
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: registry.redhat.io/rhel8/mariadb-105:latest
        env:
        - name: MYSQL_USER
          value: "user1"
        - name: MYSQL_PASSWORD
          value: "password123"
        - name: MYSQL_DATABASE
          value: "testdb"
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpass"
        ports:
        - containerPort: 3306
          name: mariadb
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: test
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306